# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_convolutions.ipynb.

# %% auto 0
__all__ = ['conv']

# %% ../nbs/07_convolutions.ipynb 2
# import torch
# from torch import nn

# from torch.utils.data import default_collate
import tensorflow as tf
from typing import Mapping

import sys
sys.path.append('..')
from .training import *
from .datasets import *

# %% ../nbs/07_convolutions.ipynb 74
def conv(ni, nf, ks=3, stride=2, act=True):
    # res = nn.Conv2d(ni, nf, stride=stride, kernel_size=ks, padding=ks//2)
    # if act: res = nn.Sequential(res, nn.ReLU())
    return tf.keras.layers.Conv2D(nf, strides=stride, kernel_size=ks, padding='same', activation='relu' if act else None)
    # return res
